### PR TITLE
ci(gha): fix missing tag in kubectl binary

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add `fetch-depth` to fetch all history for tags.

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Comment by niladrih** [comment]
> How can we test it before approving ?

Umm... you could try on your own fork. You can take this change, and create a branch, and create a github release with a new tag.

**Review by pchandra19 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> How can we test it before approving ?

Proof: https://github.com/tiagolobocastro/mayastor-extensions/actions/runs/5273295855

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by niladrih — COMMENTED** [review]
nit: maybe move this new 4th step right next to the first step, because they are of the same context.

**Comment by tiagolobocastro** [comment]
> nit: maybe move this new 4th step right next to the first step, because they are of the same context.

Indeed, done!

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
