### PR TITLE
feat(chart/csi-node): add nvme kato parameter

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add parameter to configure keep alive timeout.
By default it's set to "" meaning it's the system default (5).

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
We have another good old bors bork
bors retry

**Comment by tiagolobocastro** [comment]
bors ping

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
I wrote the status directly to the commit, seems to have unborked bors.. let's try again:
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
Something doesn't seem right...
```
ERROR: Error fetching remote repo 'origin'

hudson.plugins.git.GitException: Failed to fetch from https://github.com/openebs/mayastor-extensions.git

	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1003)

	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1244)

	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1308)

	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)

	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)

	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)

	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:829)

Caused by: hudson.plugins.git.GitException: Command "git submodule foreach --recursive git reset --hard" returned status code 128:

stdout: Entering 'dependencies/control-plane'

HEAD is now at 0d0e7e04 chore(bors): merge pull request #407

Entering 'dependencies/control-plane/rpc/api'

HEAD is now at f54c0cc feat: report hostnqn through registration and info messages (#39)

Entering 'dependencies/control-plane/utils/dependencies'

HEAD is now at 79e3fc7 feat(nvmeadm): add hostnqn config parameter (#16)

Entering 'dependencies/control-plane/utils/dependencies/h2'

HEAD is now at 929f268 fix header


stderr: fatal: No url found for submodule path 'rpc/api' in .gitmodules

```

**Comment by tiagolobocastro** [comment]
looks like rpc could not be clean because it was owned by root?? should work now:
bors try

**Review by sinhaashish — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Review by chriswldenyer — COMMENTED** [review]
LGTM

**Pull request merged**
