### PR TITLE
Add partial rebuild disable and various fixes

### PR DESCRIPTION
**Pull request by tiagolobocastro**
feat(helm): add var to disable partial rebuilds
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(helm): unbound helm var access
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    ci: printenv before image build test
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    ci(release/script): avoid unbound var access
    
    Ensure helm dep var is set before we use it (cleanup).
    Rename it to capitals to make clear its global.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    ci(helm/devel-rel): don't die when already in rel
    
    When we're already in the release branch, don't fail.
    On the other hand, do fail if on a different version.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Review by blaisedias — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
