### PR TITLE
feat(upgrade-job): add helm value set for jaeger-operator update

### PR DESCRIPTION
**Pull request by niladrih**
Requires PR 473

Screenshot 2024-04-09 at 11 00 09 AM

### CODE REVIEW

**Review by avishnu — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
