### PR TITLE
fix(dependencies): pin git submodules to release/2.0 branches

### PR DESCRIPTION
**Pull request by niladrih**
Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

Pin dependency git submodule repos to the most recent commit in the release/2.0 branch.

### CODE REVIEW

**Comment by niladrih** [comment]
bors try

**Review by datacore-vkumar — APPROVED** [review]
LGTM

**Review by tiagolobocastro — APPROVED** [review]
Please wait till "https://github.com/openebs/mayastor-control-plane/pull/343" is in, then update submodules so it's all also aligned properly.

**Comment by niladrih** [comment]
bors try

**Comment by niladrih** [comment]
bors merge

**Pull request merged**
