### PR TITLE
fix(csi-resizer): lower memory usage on large clusters

### PR DESCRIPTION
**Pull request by tiagolobocastro**
If CSI driver being used supports online expansion, it might be desirable to set handle-volume-inuse-error to false - to save costs associated with watching all pods in the cluster.

## Description
Since we support online expansion, it makes sense to disable it.

## Motivation and Context

Reduce memory consumption on clusters with large number of pods.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Resolves https://github.com/openebs/mayastor/issues/1774

**Review by niladrih — APPROVED** [review]
Could surround it in `""`... would look nice sitting next to the other args.

**Comment by tiagolobocastro** [comment]
> Could surround it in `""`... would look nice sitting next to the other args.

Indeed, done

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
