### PR TITLE
fix(etcd): point to specific commit of the bitnami repo

### PR DESCRIPTION
**Pull request by tiagolobocastro**
See: https://github.com/bitnami/charts/issues/10539
Resolves: https://github.com/openebs/mayastor-extensions/issues/1

### CODE REVIEW

**Review by vharsh — APPROVED** [review]
lgtm

**Review by GlennBullingham — APPROVED** [review]
LGTM

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
