### PR TITLE
feat(hot-upgrade) . all hot upgrade code- merge from develop to release2.1 .

### PR DESCRIPTION
**Pull request by sinhaashish**
PR #162  is closed as the commits were squashed there. @tiagolobocastro  gave a good suggestion to have a PR from develop to release without squashing the commits so that we can have the commits trace in release2.1 branch as well. This PR does the same,

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Review by avishnu — APPROVED** [review]

**Comment by sinhaashish** [comment]
bors merge

**Comment by avishnu** [comment]
bors try

**Comment by avishnu** [comment]
bors merge

**Comment by avishnu** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
