### PR TITLE
feat(supportability): update etcd pagination fetch method

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**
#### Changes in the PR.

- Updates the control-plane submodule.
- Uses the `get_values_paged_all` method to compute range.

### CODE REVIEW

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Review by tiagolobocastro — APPROVED** [review]

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors try

**Comment by abhilashshetty04** [comment]
bors ping

**Comment by Abhinandan-Purkait** [comment]
bors try-

**Comment by Abhinandan-Purkait** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors cancel

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors try

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Pull request merged**
