### PR TITLE
chore(submodule): update control-plane submodule

### PR DESCRIPTION
**Pull request by dsharma-dc**

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by dsharma-dc** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
Please upgrade dep to `40388e7293162a4d84b86346ca40f134c1d31c5d`  which includes an openapi fix which will be useful for plugin.

**Comment by dsharma-dc** [comment]
> Please upgrade dep to 40388e7293162a4d84b86346ca40f134c1d31c5d which includes an openapi fix which will be useful for plugin.

Updated to latest  i.e. 455773003ffe2625be0797360574e2d1d08fa543

**Comment by dsharma-dc** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
