### PR TITLE
chore: use silence log env variable for control-plane components

### PR DESCRIPTION
**Pull request by tiagolobocastro**
chore(nix): upgrade to release channel

Also pin the rust nightly to the same day as the control-plane.

---

chore: use silence log env variable for control-plane components

Use the env var RUST_LOG_SILENCE which silences overly verbose components.
By default we use whatever is set during compile time.
A common base.logSilenceLevel is added to set a common silence for all components but each
component can also override it.

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Review by vharsh — APPROVED** [review]
lgtm

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
The build passed, but the PR didn't get merged... :/
Let's try again:
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
