### PR TITLE
Data plane upgrade binary

### PR DESCRIPTION
**Pull request by niladrih**
Changes:
- Refactors upgrade-job, moves most of the code from the bin directory to the outer upgrade library.
- Adds the restart-io-engines binary.

The restart-io-engines should go through all io-engine Pods restarting them, and then circling back and restarting them again, all while adhering to the 'upgrade' way of things.

### CODE REVIEW

**Review by tiagolobocastro — CHANGES_REQUESTED** [review]
This seems like a huge change to be adding near release, I'd like to understand this a bit better before.

**Comment by niladrih** [comment]
> This seems like a huge change to be adding near release, I'd like to understand this a bit better before.


That makes sense. I think I too want this to sit for now.

**Comment by sinhaashish** [comment]
IMHO using a flag to skip the validation will be musch simpler change to do , rather than refactoring

**Review by dsavitskiy — APPROVED** [review]

**Comment by niladrih** [comment]
This is no longer needed. Closing this PR.

**Comment by tiagolobocastro** [comment]
> This is no longer needed. Closing this PR.

I think it's still useful to have this sort of thing @niladrih.
Example: someone manages their cluster with Argo. After an upgrade the pods still need restarting. 

We'd need some sort of upgrade-less restart or even have the kubectl-mayastor plugin itself do it.

**Comment by niladrih** [comment]
Alright, I'd have set this up again.. hmm.

**Comment by niladrih** [comment]
I've filed this issue: https://github.com/openebs/mayastor/issues/1674

**Pull request closed without merging**
