### PR TITLE
fix(upgrade-job): wait for event worker to exit for errors

### PR DESCRIPTION
**Pull request by niladrih**
The upgrade job main thread starts a worker thread which listens for events and publishes them (as kubernetes events). When the upgrade method exits, the 'EventRecorder' instance for it is dropped. This in turn drops the event channel (used to pass events to the event worker) and also the handle to event worker. The event worker does not have enough time after the channel is dropped, to publish its events and exit. 

This PR defers all of the event publishes and actual upgrade steps to an inner function. The caller of this function makes sure the event loop exits before returning.

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by tiagolobocastro — COMMENTED** [review]
Not sure if waiting on a drop is a good practice...
Could we achieve the same some other way?

**Comment by tiagolobocastro** [comment]
> > Not sure if waiting on a drop is a good practice... Could we achieve the same some other way?
> 
> Sure, could you suggest a suitable pattern for fleshing out this destructor-like tool.

What about just waiting for the work to complete in `shutdown_worker`?

**Comment by niladrih** [comment]
> > > Not sure if waiting on a drop is a good practice... Could we achieve the same some other way?
> > 
> > 
> > Sure, could you suggest a suitable pattern for fleshing out this destructor-like tool.
> 
> What about just waiting for the work to complete in `shutdown_worker`?

So, no change?

**Comment by niladrih** [comment]
Just noticed that shutdown worker doesn't guarantee publish of error events. Only guarantees publish of successful upgrade. I think this is still required. What might be a good alternative to the drop thing, @tiagolobocastro ?

**Comment by niladrih** [comment]
Updated code in this PR to not use the EventRecorder's Drop. Instead it moves the event recorder to one level up in the calling sequence. This let's the event recorder's shutdown_worker method wait for the loop to exit.

**Review by sinhaashish — APPROVED** [review]
Tested & LGTM

**Review by abhilashshetty04 — APPROVED** [review]

**Comment by niladrih** [comment]
bors merge

**Pull request merged**
