### PR TITLE
feat(call-home): add callhome endpoint and encryption key

### PR DESCRIPTION
**Pull request by niladrih**
Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

This PR adds the following:
- The encryption public key for at-rest encrypting of call-home metrics data
- The API endpoint for call-home transmitter
- Build changes to include the encryption key in the container image

### CODE REVIEW

**Comment by niladrih** [comment]
bors try

**Review by avishnu — APPROVED** [review]
LGTM.

**Review by datacore-vkumar — APPROVED** [review]
LGTM

**Comment by niladrih** [comment]
bors try

**Comment by niladrih** [comment]
bors merge

**Pull request merged**
