### PR TITLE
feat(plugin/rebuild_history): adding new cmd to get volume rebuild hi…

### PR DESCRIPTION
**Pull request by abhilashshetty04**

### CODE REVIEW

**Review by tiagolobocastro — COMMENTED** [review]
Please update README as well

**Review by tiagolobocastro — APPROVED** [review]
Please squash commits

**Comment by abhilashshetty04** [comment]
bors try

**Comment by abhilashshetty04** [comment]
bors merge

**Review by dsharma-dc — APPROVED** [review]

**Comment by abhilashshetty04** [comment]
bors merge

**Pull request merged**
