### PR TITLE
chore: add config for reactor freeze detection

### PR DESCRIPTION
**Pull request by blaisedias**
Modify io-engine-daemonset.yaml to optionally add the
reactor freeze detection command line argument
for mayastor io-engine

### CODE REVIEW

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Review by avishnu — APPROVED** [review]
Lgtm

**Comment by tiagolobocastro** [comment]
Why do we need this? IMHO it'd be preferred to add explicit options for what we need as that would be closer to what end users would do.

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by blaisedias** [comment]
bors merge

**Pull request merged**
