### PR TITLE
build: update dependencies and release.sh

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Update to dependencies where a base release.sh is present which can be used by the various mayastor repos.

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
Worker was running out of space...
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
