### PR TITLE
Backport fixes to release/2.7

### PR DESCRIPTION
**Pull request by tiagolobocastro**
build: update controller dep
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    feat(chart): add requestTimeout for core-agent container
    
    Signed-off-by: Oleksandr Shalbanov <oleksandr.shalbanov.9@fntsoftware.com>

---

    chore(bors): merge pull request #534
    
    534: refactor: use controllerrevisions to filter data-plane Pods for upgrade r=niladrih a=niladrih
    
    Co-authored-by: Niladri Halder <niladri.halder26@gmail.com>
    Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

---

    fix(chart): allow scaling etcd via replicaCount and Helm upgrade
    
    The etcd chart dynamically sets this value based on whether Helm is
    installing or upgrading.
    
    Signed-off-by: Mike Beaumont <mjboamail@gmail.com>

---

    chore(bors): merge pull request #529
    
    529: feat(eventing): add error logs and retries for rest api requests r=niladrih a=niladrih
    
    Co-authored-by: Vandana Varakantham <vandana.varakantham@datacore.com>
    Co-authored-by: Niladri Halder <niladri.halder26@gmail.com>
    Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

---

    chore: update docs URL in helm chart NOTES.txt
    
    Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

---

    chore(bors): merge pull request #517
    
    517: Cherry-pick changes from mayastor PR r=tiagolobocastro a=tiagolobocastro
    
    Cherry-pick user changes from stale mayastor PR.
    Modified the initContainers change as we now have many init containers.
    
    Co-authored-by: Joshua Carnes <jcarnes1@bellsouth.net>
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by niladrih — CHANGES_REQUESTED** [review]
This contains changes to upgrade, but it's incomplete. It's got half of the 'Upgrade enhancements changes'. Might be a good idea to go either way with this.

**Comment by niladrih** [comment]
If you'd like to go all the way with the upgrade enhancements, you'd need this commit: fe6026a5b8a59d8f27af3ab96eeefe7ff86f33e6

**Comment by tiagolobocastro** [comment]
> If you'd like to go all the way with the upgrade enhancements, you'd need this commit: [fe6026a](https://github.com/openebs/mayastor-extensions/commit/fe6026a5b8a59d8f27af3ab96eeefe7ff86f33e6)

Done, PTAL

**Review by niladrih — APPROVED** [review]
LGTM

**Comment by niladrih** [comment]
We might want to use localpv-provisioner v4.1.2 with release/2.7's helm chart.

**Comment by tiagolobocastro** [comment]
> We might want to use localpv-provisioner v4.1.2 with release/2.7's helm chart.

That's not a backport, please add that as separate PR.
bors merge

**Pull request merged**
