### PR TITLE
Helm Variables

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add missing variables which were used on v1 by a user.

## Description

Makes several options configurable through helm.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.

### CODE REVIEW

**Review by niladrih — APPROVED** [review]
Yeah, makes sense.

**Review by dsharma-dc — APPROVED** [review]
> Add missing variables which were used on v1 by a user.

What does `missing` mean here? Did we at some point deliberately remove these variables and now re-adding them?

**Comment by tiagolobocastro** [comment]
> > Add missing variables which were used on v1 by a user.
> 
> What does `missing` mean here? Did we at some point deliberately remove these variables and now re-adding them?

Added to the raw yaml, but now that we use helm one can't simply edit the yaml anymore...
Perhaps we should consider adding custom env variables..

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
