### PR TITLE
Cherry-pick PR 579 and PR 584

### PR DESCRIPTION
**Pull request by tiagolobocastro**
chore: fix helm-testing versioning in publish-chart-yaml
    
    Replace hard coded patch and minor values of 0,
    with values derived from the chart version
    
    That way we get versions derived from chart/Chart.yaml,
    like 2.7.2-... instead of hard coded values like 2.7.0-... or 2.0.0-....
    
    Signed-off-by: Blaise Dias <blaise.dias@datacore.com>

---

    ci: various release chart update fixes
    
    Don't update the chart on a pre-release
    Set missing base branch for pull-request
    Add stricter release validation
    Add more tests
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by niladrih** [comment]
@tiagolobocastro could you pull in the krew bot change into this PR as well?

**Review by sinhaashish — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
Network error it seems...
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
