### PR TITLE
fix: make darwin images statically linked

### PR DESCRIPTION
**Pull request by tiagolobocastro**
fix: make darwin images statically linked

Openssl and libiconv were dynamically linked, which won't work... as they were pointing
to the nix store path.
Sadly on darwin pkgsStatic is not really static:
https://github.com/NixOS/nixpkgs/issues/120862
So we have to build our own static openssl and libiconv, which can take sometime.
todo: use cachix to speed up most builds.

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

feat(nix-shell): add support for aarch64-darwin

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Until we have an aarch64-darwin GitHub runner, we can run the x86 Darwin binary through emulation.

**Review by avishnu — APPROVED** [review]
Lgtm thanks.

**Review by Abhinandan-Purkait — APPROVED** [review]
Thanks 👍🏻

**Review by abhilashshetty04 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
