### PR TITLE
Cherry-pick PR #474

### PR DESCRIPTION
**Pull request by niladrih**
This PR cherry-picks the commits from PR 474 to release/2.6 branch

### CODE REVIEW

**Review by avishnu — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Comment by sinhaashish** [comment]
bors try

**Comment by sinhaashish** [comment]
bors cancel

**Comment by sinhaashish** [comment]
bors ping

**Comment by sinhaashish** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
