### PR TITLE
feat(helm-docs): autogenerate helm docs

### PR DESCRIPTION
**Pull request by tiagolobocastro**
ci: add helm-docs Jenkins test

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

chore: update values.yaml and update README

Add comments notation and tidy up some values.

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

feat(helm-docs): autogenerate helm docs

Add helm-docs to nix-shell.
Add template for generating the README.
Add script that generates the README.

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

chore(shell): add commitlinter as git pre-commit hook

Add the commitlinter as a pre-commit hook

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

chore: update control-plane dep

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

fix: update image pull policy on tag

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by pchandra19 — APPROVED** [review]

**Review by avishnu — APPROVED** [review]
lgtm

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
