### PR TITLE
chore: submodule update #612

### PR DESCRIPTION
**Pull request by abhilashshetty04**

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Update the README as well now that the cmd output has changed

**Comment by tiagolobocastro** [comment]
Update submodule to latest control-plane as this clashes with @Abhinandan-Purkait  PR

**Review by tiagolobocastro — APPROVED** [review]

**Comment by abhilashshetty04** [comment]
bors merge

**Review by sinhaashish — APPROVED** [review]

**Comment by abhilashshetty04** [comment]
bors merge

**Pull request merged**
