### PR TITLE
fix(gha/bot): update README when creating develop=>release PR

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Review by blaisedias — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors ping

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
Bors is broken AGAIN. If the try passes I'll simply merge manually.

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Pull request merged**
