### PR TITLE
feat(plugin/list_snapshots): add new cli for listing snapshots

### PR DESCRIPTION
**Pull request by dsharma-dc**

### CODE REVIEW

**Review by tiagolobocastro — COMMENTED** [review]
You need to upgrade the control-plane dependency otherwise the kubectl-mayastor binary won't have this new subcommand...

**Comment by dsharma-dc** [comment]
> You need to upgrade the control-plane dependency otherwise the kubectl-mayastor binary won't have this new subcommand...

Updated the submodule.

**Review by tiagolobocastro — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by dsharma-dc** [comment]
bors merge

**Comment by dsharma-dc** [comment]
bors try

**Comment by dsharma-dc** [comment]
bors try

**Comment by sinhaashish** [comment]
bors merge

**Review by sinhaashish — APPROVED** [review]

**Pull request merged**
