### PR TITLE
Update `loki-stack` and set `health_check_targets: false`.

### PR DESCRIPTION
**Pull request by reitermarkus**
## Motivation and Context

Fixes https://github.com/openebs/mayastor/issues/1560.

## Regression

No.

## How Has This Been Tested?

Running with current helm chart and this configuration:

```yaml
loki-stack:
  promtail:
    config:
      # TODO: Remove once Mayastor chart is updated.
      file: |
        server:
          log_level: {{ .Values.config.logLevel }}
          http_listen_port: {{ .Values.config.serverPort }}
          {{- tpl .Values.config.snippets.extraServerConfigs . | nindent 2 }}

        clients:
          - url: {{ tpl .Values.config.lokiAddress . }}
          {{- with .Values.config.snippets.extraClientConfigs }}
          {{- toYaml . | nindent 2 }}
          {{- end }}

        positions:
          filename: /run/promtail/positions.yaml

        scrape_configs:
          {{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}
          {{- tpl .Values.config.snippets.extraScrapeConfigs . | nindent 2 }}

      snippets:
        extraServerConfigs: |-
          health_check_target: false
```

The `{{- tpl .Values.config.snippets.extraServerConfigs . | nindent 2 }}` part is included by default in newer versions of the `loki-stack` chart.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]
@reitermarkus You need to remove the `.` from your commit message for the commit lint.

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> @reitermarkus You need to remove the `.` from your commit message for the commit lint.

Also lowercase **u**pdate

**Comment by tiagolobocastro** [comment]
@reitermarkus, also please regenerate the docs:
> ./scripts/helm/generate-readme.sh

We need to add this to GHA too I guess, I'll fix this on another PR.

**Comment by reitermarkus** [comment]
Given https://github.com/openebs/mayastor-extensions/pull/387 is merged, should I still update this PR?

**Comment by tiagolobocastro** [comment]
> Given #387 is merged, should I still update this PR?

Yes please, 387 was merged to the release branch, this is targetting develop

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@niladrih PTAL and sequence merge whichever way you think is better for the upgrade changes

**Comment by niladrih** [comment]
bors merge

**Pull request merged**
