### PR TITLE
fix(nix): use builtins.path instead of builtins.filterSource

### PR DESCRIPTION
**Pull request by niladrih**
Jenkins CI uses '@' in its workspace directory name. Nix seems to not like that. builtins.path { name = ... } lets you choose the directory name when copying the source files to the nix store directory.

### CODE REVIEW

**Comment by niladrih** [comment]
bors try

**Comment by niladrih** [comment]
bors cancel

**Comment by niladrih** [comment]
bors try

**Comment by niladrih** [comment]
bors cancel

**Review by pchandra19 — APPROVED** [review]

**Comment by pchandra19** [comment]
bors merge

**Review by sinhaashish — APPROVED** [review]

**Comment by sinhaashish** [comment]
bors merge

**Pull request merged**
