### PR TITLE
Build aarch64-linux binaries for the kubectl-plugin

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Cross compile aarch64-linux static binary from x86_64-linux.

## Description
Refactor the static binary building to allow cross-compilation.
Also simplifies adding a new binary by adding generic builders.

## Motivation and Context
Building aarch64 binaries.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.

### CODE REVIEW

**Review by abhilashshetty04 — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]
LGTM. Thanks 🚀

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
