### PR TITLE
chore(upgrade-job): bump the expected umbrella chart version to 4.0

### PR DESCRIPTION
**Pull request by niladrih**

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Review by w3aman — APPROVED** [review]

**Comment by niladrih** [comment]
bors merge

**Review by dsharma-dc — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by niladrih** [comment]
bors merge

**Comment by pchandra19** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
