### PR TITLE
fix(serialization): update dependency to fix get node issue

### PR DESCRIPTION
**Pull request by sinhaashish**

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
This is pointing to develop, must update hash to release once control-plane PR is merged

**Review by tiagolobocastro — APPROVED** [review]
On the basis the hash is update after control-plane PR is merged..

**Comment by sinhaashish** [comment]
> On the basis the hash is update after control-plane PR is merged..

Does this seems ok ?

**Review by tiagolobocastro — APPROVED** [review]

**Review by hrudaya21 — APPROVED** [review]

**Comment by sinhaashish** [comment]
bors merge

**Pull request merged**
