### PR TITLE
Cherry-pick #59 into release/2.0 branch

### PR DESCRIPTION
**Pull request by niladrih**
Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

This PR cherry-picks #59 into release/2.0 branch.

### CODE REVIEW

**Comment by niladrih** [comment]
bors try

**Comment by niladrih** [comment]
bors try

**Comment by tiagolobocastro** [comment]
@niladrih the upgrade operator is not for release/2.0? If not then we don't need this cherry pick?

**Comment by niladrih** [comment]
Tested and verified that `OnDelete` updateStrategy make manual-delete available on the same helm upgrade as the one in which it is introduced, i.e. changing the updateStrategy to OnDelete on 2.1.0 helm chart will not delete the io-engine pods when upgrading from 2.0.0 to 2.1.0, there is no need to change the upgrade strategy on the previous release (as I had assumed). Closing this PR.

**Pull request closed without merging**
