### PR TITLE
feat(call-home): use version_info crate to generate git version

### PR DESCRIPTION
**Pull request by niladrih**
This ports the changes from #125 for release/2.0 branch

### CODE REVIEW

**Comment by niladrih** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by avishnu — APPROVED** [review]
lgtm

**Comment by niladrih** [comment]
bors merge

**Comment by niladrih** [comment]
bors retry

**Comment by niladrih** [comment]
bors merge

**Pull request merged**
