### PR TITLE
Cherry-pick #109 to develop branch

### PR DESCRIPTION
**Pull request by niladrih**
Changes:
- Raise memory limit for agent-core container to 128MiB
- Raise memory request for agent-core container to 32MiB
- Raise memory limit for HA cluster agent to 64MiB

Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Comment by niladrih** [comment]
bors try

**Review by avishnu — APPROVED** [review]
Lgtm

**Comment by niladrih** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Comment by niladrih** [comment]
bors merge

**Pull request merged**
